# Generated by Django 5.2.10 on 2026-01-17 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='file', max_length=50)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField()),
                ('access', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='protected', max_length=50)),
            ],
            options={
                'verbose_name': 'MediaFile',
                'verbose_name_plural': 'MediaFiles',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.'),
        ),
    ]
