# Generated by Django 5.2.10 on 2026-01-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediafile_address_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
    ]
