# Generated by Django 5.2.10 on 2026-01-18 15:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_remove_orderitem_discounted_amount_and_more'),
        ('products', '0002_productvariant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('requires_loyalty', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('order', 'Order'), ('item', 'Item'), ('category', 'Category')], default='order', max_length=20)),
                ('discount_type', models.CharField(choices=[('fix', 'Fix'), ('percentage', 'Percentage')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('scope', models.CharField(choices=[('order', 'Order'), ('item', 'Item'), ('category', 'Category')], default='order', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('discount_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.discountrule')),
            ],
            options={
                'verbose_name': 'Applied Discount',
                'verbose_name_plural': 'Applied Discounts',
                'ordering': ('order', 'discount_rule'),
                'unique_together': {('order', 'discount_rule')},
            },
        ),
    ]
