# Generated by Django 5.2.10 on 2026-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_authenticated_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loyalty_member',
            field=models.BooleanField(default=False, help_text='Flag indicating if user is a loyalty program member'),
        ),
    ]
