# Generated by Django 5.2.10 on 2026-01-19 08:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productvariant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total quantity of stock items', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Reserved quantity of stock items', validators=[django.core.validators.MinValueValidator(0)])),
                ('to_produce_quantity', models.IntegerField(default=0, help_text='Total quantity of stock items', validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_quantity', models.IntegerField(default=0, help_text='Remaining quantity of stock items', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_unlimited_stock', models.BooleanField(default=False, help_text='Unlimited stock items')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='products.product', unique=True)),
                ('product_variant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='products.productvariant', unique=True)),
            ],
            options={
                'verbose_name': 'Stock Inventory',
                'verbose_name_plural': 'Stock Inventories',
                'ordering': ['product_variant', 'product', 'total_quantity'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('type', models.CharField(choices=[('inward', 'Inward'), ('outward', 'Outward')], default='inward')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stock transaction metadata')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction', to='inventory.stockinventory')),
            ],
            options={
                'verbose_name': 'Stock Inventory Transaction',
                'verbose_name_plural': 'Stock Inventory Transactions',
                'ordering': ('-created_at', 'inventory'),
            },
        ),
    ]
