# Generated by Django 5.2.10 on 2026-01-17 14:17

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_mediafile_address_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Set to False to deactivate.')),
                ('order_number', models.IntegerField(default=orders.models.get_order_number, editable=False, unique=True)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EUR')], default='₹', max_length=64)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('handed_over', 'Handed Over'), ('cancelled', 'Cancelled')], default='created', max_length=64)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('payment_pending', 'Payment Pending'), ('payment_refund', 'Payment Refund'), ('payment_refunded', 'Payment Refunded')], default='payment_pending', max_length=64)),
                ('payment_mode', models.CharField(choices=[('upi', 'UPI'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('other', 'Other')], default='online', max_length=20)),
                ('delivered_on', models.DateTimeField(blank=True, help_text='actual delivered date', null=True)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
