# Generated by Django 5.2.10 on 2026-01-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discounted_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_coupon_code_applied',
        ),
    ]
